engines:
  rubocop:
    enabled: true
    channel: "rubocop-0-89"
  scss-lint:
    enabled: true
  shellcheck:
    enabled: true
  eslint:
    enabled: true
  coffeelint:
    enabled: true
  brakeman:
    enabled: false # codeclimate's brakeman is stuck in rails 5 rules
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - "**.rb"
  - "**.ru"
  - "**.js"
  - "**.coffee"
  - "**.scss"
  - "**.haml"
  - Gemfile.lock
exclude_paths:
- config/
- db/
- spec/
- public/
- app/assets/stylesheets/bootstrap-accessibility.css
- app/assets/javascripts/bootstrap*
- app/assets/stylesheets/leaflet_overrides.scss
