---
fail_on_violations: true
ruby:
  config_file: .rubocop.yml
haml:
  config_file: .haml-lint.yml
scss:
  config_file: .scss-lint.yml
eslint:
  config_file: .eslintrc
  ignore_file: .esignore
jshint:
  enabled: false
