inherit_from: .rubocop_todo.yml
require: rubocop-rails
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
  TargetRailsVersion: 5.0

Rails:
  Enabled: true

Naming/FileName:
  Exclude:
    - 'Guardfile'
    - 'Gemfile'
    - 'Gemfile.lock'

Style/StringLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': ()
    '%w': ()

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: with_first_parameter, with_fixed_indentation
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation


Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Configuration parameters: Include.
# Include: app/**/*.rb, config/**/*.rb, db/**/*.rb, lib/**/*.rb
Rails/Output:
  Exclude:
    - 'config/unicorn.rb'
    - 'db/seeds.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '**/*.rake'
    - 'config/**/*.rb'

Metrics/LineLength:
  Max: 140

# Remove the following once the code style matches
Metrics/MethodLength:
  Max: 34
Metrics/AbcSize:
  Max: 33
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 171
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/PerceivedComplexity:
  Max: 9

# Places we use update_all, etc even though it skips validations.
Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/20190317023129_finished_boolean.rb'
    - 'db/seeds.rb'
