inherit_from: .rubocop_todo.yml
require: rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
  TargetRailsVersion: 6.0

Rails:
  Enabled: true

Naming/FileName:
  Exclude:
    - 'Guardfile'
    - 'Gemfile'
    - 'Gemfile.lock'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: with_first_parameter, with_fixed_indentation
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/StringLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': ()
    '%w': ()

Style/Documentation:
  Enabled: false

# Configuration parameters: Include.
# Include: app/**/*.rb, config/**/*.rb, db/**/*.rb, lib/**/*.rb
Rails/Output:
  Exclude:
    - 'config/unicorn.rb'
    - 'db/seeds.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '**/*.rake'
    - 'config/**/*.rb'

Layout/LineLength:
  Max: 140

# Places we use update_all, etc even though it skips validations.
Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/20190317023129_finished_boolean.rb'
    - 'db/seeds.rb'
