inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - 'Rakefile'
    - 'config.ru'
    - 'lib/**/*.rake'
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
  TargetRailsVersion: 4.0

Rails:
  Enabled: true

Style/FileName:
  Exclude:
    - 'Guardfile'
    - 'Gemfile'
    - 'Gemfile.lock'

Style/StringLiterals:
  Enabled: false

# Stop hound and codeclimate fighting
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': ()
    '%w': ()

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: with_first_parameter, with_fixed_indentation
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/LineLength:
  Max: 120

# turn these back on in Rails 5
Rails/HttpPositionalArguments: # See https://github.com/bbatsov/rubocop/issues/3629
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Configuration parameters: Include.
# Include: app/**/*.rb, config/**/*.rb, db/**/*.rb, lib/**/*.rb
Rails/Output:
  Exclude:
    - 'config/unicorn.rb'
    - 'db/seeds.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '**/*.rake'
    - 'config/**/*.rb'

# Remove the following once the code style matches
Metrics/MethodLength:
  Max: 34
Metrics/AbcSize:
  Max: 31
Metrics/ClassLength:
  Max: 179
Metrics/CyclomaticComplexity:
  Max: 11
Metrics/PerceivedComplexity:
  Max: 9
