# service configuration for our dockerized Rails app
app:
  # use the Dockerfile next to this file
  build: .
  # sources environment variable configuration for our app
  env_file: .env
  # rely on the RAILS_ENV value of the host machine
  environment:
    RAILS_ENV: $RAILS_ENV
  # makes the app container aware of the DB container
  links:
    - db
    - elasticsearch
  # expose the port we configured Unicorn to bind to
  ports:
    - "3000:3000"

# service configuration for our database
db:
  # use the preferred version of the official Postgres image
  # see https://hub.docker.com/_/postgres/
  image: postgres:9.4.5
  # persist the database between containers by storing it in a volume
  volumes:
    - postgres-data:/var/lib/postgresql/data

# Elasticsearch full-text search engine
elasticsearch:
  image: elasticsearch:1.4.5
  volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
