default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: growstuff_dev
  user: postgres
  password: postgres
  host: <%= ENV.fetch("DATABASE_HOST") { 'db' } %>


test:
  <<: *default
  database: growstuff_test
  user: postgres
  password: postgres
  host: <%= ENV.fetch("DATABASE_HOST") { 'db' } %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
