# To use, copy secrets.yml.example to secrets.yml (which is
# .gitignored) and fill in the appropriate values.

# The secrets added to this file are accessible via Rails.application.secrets

# Be sure to restart your server when you modify this file.

# We are progressively moving config variables out of
# config/environments/*.rb to secrets.yml.
# Please do not add new config variables to config/environments.
# There are however a couple of exceptions to this, particularly config
# variables used by the assets pipeline, which cannot access ENV.  These
# include:
#   mapbox_map_id

# NOTE: please prefix all environment variables with GROWSTUFF_ to make
# it easy to identify which were set by us vs. the system or anyone else

default: &default
  # name that appears on the site, eg. in page titles
  GROWSTUFF_SITE_NAME: Growstuff (dev)

  # Mandrill is used to send transactional email (eg. signup
  # confirmations).  If using Heroku connect to Mandrill via Heroku addons
  # list then go to tools menu (upper right) and choose "SMTP and API
  # Credentials"
  GROWSTUFF_MANDRILL_USERNAME: "dummy"
  GROWSTUFF_MANDRILL_APIKEY: "dummy"

  # Mailchimp is used for subscribing/unsubscribing people from the newsletter
  # To fetch list IDs using Gibbon (and thus find the ID of your newsletter):
  #   $ rails c
  #   Gibbon::API.api_key = '...'
  #   gb = Gibbon::API.new
  #   puts gb.lists.list.to_yaml
  GROWSTUFF_MAILCHIMP_APIKEY: "dummy"
  GROWSTUFF_MAILCHIMP_NEWSLETTER_ID: "dummy"

  # Used for connecting member accounts to Twitter
  # Get Twitter key from https://dev.twitter.com/apps
  GROWSTUFF_TWITTER_KEY: "dummy"
  GROWSTUFF_TWITTER_SECRET: "dummy"

  # Used for connecting member accounts to Flickr
  # Get Flickr key from http://www.flickr.com/services/apps/create/apply/
  GROWSTUFF_FLICKR_KEY: "dummy"
  GROWSTUFF_FLICKR_SECRET: "dummy"

  # Paypal is used for payments, obviously.
  GROWSTUFF_PAYPAL_USERNAME: "dummy"
  GROWSTUFF_PAYPAL_PASSWORD: "dummy"
  GROWSTUFF_PAYPAL_SIGNATURE: "dummy"

  # Elasticsearch is used for flexible search and it requires another component
  # to be installed. To make it easy for people who don't need to test this feature
  # it's been turned off for test and development environment as a default.
  # If you want to test this functionality, install elasticsearch and
  # set this flag to "true".
  GROWSTUFF_ELASTICSEARCH: "false"

development:
  <<: *default
  # Your secret key for verifying the integrity of signed cookies.
  # If you change this key, all old signed cookies will become invalid!
  # Make sure the secret is at least 30 characters and all random,
  # no regular words or you'll be exposed to dictionary attacks.
  # run 'rake secret' to generate your own
  secret_key_base: 'b1b67abb399261478f4721e704eb3851466daf60d9cd2b53a1839b056d641c4c1c2a476bcaf7addc6d6548926cfd32fa5a00a8de258880257ebb5a6fd86cb08f'

test:
  <<: *default
  # run 'rake secret' to generate your own
  secret_key_base: 'be557aa019b181f201c9906663dbf8f22efb1b70b11f78035bfeda86aa7dcfd1efb184e2ee894a0ae0dc37fe67d311f38e7731fa16d8d595f2e1ef5447bae020'
  GROWSTUFF_SITE_NAME: Growstuff (test)
  GROWSTUFF_CAPYBARA_DRIVER: poltergeist

staging:
  <<: *default
  # run 'rake secret' to generate your own
  secret_key_base: "dummy"
  GROWSTUFF_SITE_NAME: Growstuff (staging)
  GROWSTUFF_ELASTICSEARCH: "true"

production:
  <<: *default
  # run 'rake secret' to generate your own
  secret_key_base: ""
