#!/usr/bin/env ruby

checks = [
  'overcommit -r',
  'script/check_contributors_md'
]

return_values = checks.collect { |t| system(t) }
failures = return_values.count(&:!)
abort "#{failures} static check(s) failed" unless failures.zero?
