#!/usr/bin/env ruby

require 'set'

changed_file_list = `git diff --name-only --diff-filter=ACMRTUXB origin/dev...`
files = Set.new changed_file_list.split
if (files.include? "Gemfile") && !(files.include? "Gemfile.lock")
  abort "Looks like you committed changes to Gemfile but not Gemfile.lock\n\n"
end
