#!/bin/bash
set -euv

gem install overcommit rubocop haml-lint bundler-audit
npm install -g eslint jshint coffeelint csslint git-guilt
pip install yamllint --user

overcommit --install
overcommit --sign
overcommit --sign pre-commit

bundle-audit update
