# frozen_string_literal: true

class CreateAustralianFoodClassificationData < ActiveRecord::Migration[5.2]
  def change
    create_table :australian_food_classification_data do |t|
      t.string :public_food_key, index: true, unique: true
      t.string :classification
      t.string :food_name
      t.decimal :energy_with_dietary_fibre_equated_kj
      t.decimal :energy_without_dietary_fibre_equated_kj
      t.decimal :moisture_water_g
      t.decimal :protein_g
      t.decimal :nitrogen_g
      t.decimal :fat_total_g
      t.decimal :ash_g
      t.decimal :total_dietary_fibre_g
      t.decimal :alcohol_g
      t.decimal :fructose_g
      t.decimal :glucose_g
      t.decimal :sucrose_g
      t.decimal :maltose_g
      t.decimal :lactose_g
      t.decimal :galactose_g
      t.decimal :maltotrios_g
      t.decimal :total_sugars_g
      t.decimal :added_sugars_g
      t.decimal :free_sugars_g
      t.decimal :starch_g
      t.decimal :dextrin_g
      t.decimal :glycerol_g
      t.decimal :glycogen_g
      t.decimal :inulin_g
      t.decimal :erythritol_g
      t.decimal :maltitol_g
      t.decimal :mannitol_g
      t.decimal :xylitol_g
      t.decimal :maltodextrin_g
      t.decimal :oligosaccharides_g
      t.decimal :polydextrose_g
      t.decimal :raffinose_g
      t.decimal :stachyose_g
      t.decimal :sorbitol_g
      t.decimal :resistant_starch_g
      t.decimal :available_carbohydrate_without_sugar_alcohols_g
      t.decimal :available_carbohydrate_with_sugar_alcohols_g
      t.decimal :acetic_acid_g
      t.decimal :citric_acid_g
      t.decimal :fumaric_acid_g
      t.decimal :lactic_acid_g
      t.decimal :malic_acid_g
      t.decimal :oxalic_acid_g
      t.decimal :propionic_acid_g
      t.decimal :quinic_acid_g
      t.decimal :shikimic_acid_g
      t.decimal :succinic_acid_g
      t.decimal :tartaric_acid_g
      t.decimal :aluminium_al_ug
      t.decimal :antimony_sb_ug
      t.decimal :arsenic_as_ug
      t.decimal :cadmium_cd_ug
      t.decimal :calcium_ca_mg
      t.decimal :chromium_cr_ug
      t.decimal :chloride_cl_mg
      t.decimal :cobalt_co_ug
      t.decimal :copper_cu_mg
      t.decimal :fluoride_f_ug
      t.decimal :iodine_i_ug
      t.decimal :iron_fe_mg
      t.decimal :lead_pb_ug
      t.decimal :magnesium_mg_mg
      t.decimal :manganese_mn_mg
      t.decimal :mercury_hg_ug
      t.decimal :molybdenum_mo_ug
      t.decimal :nickel_ni_ug
      t.decimal :phosphorus_p_mg
      t.decimal :potassium_k_mg
      t.decimal :selenium_se_ug
      t.decimal :sodium_na_mg
      t.decimal :sulphur_s_mg
      t.decimal :tin_sn_ug
      t.decimal :zinc_zn_mg
      t.decimal :retinol_preformed_vitamin_a_ug
      t.decimal :alpha_carotene_ug
      t.decimal :beta_carotene_ug
      t.decimal :cryptoxanthin_ug
      t.decimal :beta_carotene_equivalents_provitamin_a_ug
      t.decimal :vitamin_a_retinol_equivalents_ug
      t.decimal :lutein_ug
      t.decimal :lycopene_ug
      t.decimal :xanthophyl_ug
      t.decimal :thiamin_b1_mg
      t.decimal :riboflavin_b2_mg
      t.decimal :niacin_b3_mg
      t.decimal :niacin_derived_from_tryptophan_mg
      t.decimal :niacin_derived_equivalents_mg
      t.decimal :pantothenic_acid_b5_mg
      t.decimal :pyridoxine_b6_mg
      t.decimal :biotin_b7_ug
      t.decimal :cobalamin_b12_ug
      t.decimal :folate_natural_ug
      t.decimal :folic_acid_ug
      t.decimal :total_folates_ug
      t.decimal :dietary_folate_equivalents_ug
      t.decimal :vitamin_c_mg
      t.decimal :cholecalciferol_d3_ug
      t.decimal :ergocalciferol_d2_ug
      t.decimal :c25_hydroxy_cholecalciferol_25_oh_d3_ug
      t.decimal :c25_hydroxy_ergocalciferol_25_oh_d2_ug
      t.decimal :vitamin_d3_equivalents_ug
      t.decimal :alpha_tocopherol_mg
      t.decimal :alpha_tocotrienol_mg
      t.decimal :beta_tocopherol_mg
      t.decimal :beta_tocotrienol_mg
      t.decimal :delta_tocopherol_mg
      t.decimal :delta_tocotrienol_mg
      t.decimal :gamma_tocopherol_mg
      t.decimal :gamma_tocotrienol_mg
      t.decimal :vitamin_e_mg
      t.decimal :c4_t
      t.decimal :c6_t
      t.decimal :c8_t
      t.decimal :c10_t
      t.decimal :c11_t
      t.decimal :c12_t
      t.decimal :c13_t
      t.decimal :c14_t
      t.decimal :c15_t
      t.decimal :c16_t
      t.decimal :c17_t
      t.decimal :c18_t
      t.decimal :c19_t
      t.decimal :c20_t
      t.decimal :c21_t
      t.decimal :c22_t
      t.decimal :c23_t
      t.decimal :c24_t
      t.decimal :total_saturated_fatty_acids_equated_t
      t.decimal :c10_1_t
      t.decimal :c12_1_t
      t.decimal :c14_1_t
      t.decimal :c15_1_t
      t.decimal :c16_1_t
      t.decimal :c17_1_t
      t.decimal :c18_1_t
      t.decimal :c18_1w5_t
      t.decimal :c18_1w6_t
      t.decimal :c18_1w7_t
      t.decimal :c18_1w9_t
      t.decimal :c20_1_t
      t.decimal :c20_1w9_t
      t.decimal :c20_1w13_t
      t.decimal :c20_1w11_t
      t.decimal :c22_1_t
      t.decimal :c22_1w9_t
      t.decimal :c22_1w11_t
      t.decimal :c24_1_t
      t.decimal :c24_1w9_t
      t.decimal :c24_1w11_t
      t.decimal :c24_1w13_t
      t.decimal :total_monounsaturated_fatty_acids_equated_t
      t.decimal :c12_2_t
      t.decimal :c16_2w4_t
      t.decimal :c16_3_t
      t.decimal :c18_2w6_t
      t.decimal :c18_3w3_t
      t.decimal :c18_3w4_t
      t.decimal :c18_3w6_t
      t.decimal :c18_4w1_t
      t.decimal :c18_4w3_t
      t.decimal :c20_2_t
      t.decimal :c20_2w6_t
      t.decimal :c20_3_t
      t.decimal :c20_4_t
      t.decimal :c20_3w3_t
      t.decimal :c20_3w6_t
      t.decimal :c20_4w3_t
      t.decimal :c20_4w6_t
      t.decimal :c20_5w3_t
      t.decimal :c21_5w3_t
      t.decimal :c22_2_t
      t.decimal :c22_2w6_t
      t.decimal :c22_4w6_t
      t.decimal :c22_5w3_t
      t.decimal :c22_5w6_t
      t.decimal :c22_6w3_t
      t.decimal :total_polyunsaturated_fatty_acids_equated_t
      t.decimal :total_long_chain_omega_3_fatty_acids_equated_t
      t.decimal :total_undifferentiated_fatty_acids_t
      t.decimal :total_trans_fatty_acids_imputed_t
      t.decimal :c4_g
      t.decimal :c6_g
      t.decimal :c8_g
      t.decimal :c10_g
      t.decimal :c11_g
      t.decimal :c12_g
      t.decimal :c13_g
      t.decimal :c14_g
      t.decimal :c15_g
      t.decimal :c16_g
      t.decimal :c17_g
      t.decimal :c18_g
      t.decimal :c19_g
      t.decimal :c20_g
      t.decimal :c21_g
      t.decimal :c22_g
      t.decimal :c23_g
      t.decimal :c24_g
      t.decimal :total_saturated_fatty_acids_equated_g
      t.decimal :c10_1_g
      t.decimal :c12_1_g
      t.decimal :c14_1_g
      t.decimal :c15_1_g
      t.decimal :c16_1_g
      t.decimal :c17_1_g
      t.decimal :c18_1_g
      t.decimal :c18_1w5_mg
      t.decimal :c18_1w6_mg
      t.decimal :c18_1w7_g
      t.decimal :c18_1w9_mg
      t.decimal :c20_1_g
      t.decimal :c20_1w9_mg
      t.decimal :c20_1w13_mg
      t.decimal :c20_1w11_mg
      t.decimal :c22_1_g
      t.decimal :c22_1w9_mg
      t.decimal :c22_1w11_mg
      t.decimal :c24_1_g
      t.decimal :c24_1w9_mg
      t.decimal :c24_1w11_mg
      t.decimal :c24_1w13_mg
      t.decimal :total_monounsaturated_fatty_acids_equated_g
      t.decimal :c12_2_g
      t.decimal :c16_2w4_mg
      t.decimal :c16_3_g
      t.decimal :c18_2w6_g
      t.decimal :c18_3w3_g
      t.decimal :c18_3w4_g
      t.decimal :c18_3w6_mg
      t.decimal :c18_4w1_g
      t.decimal :c18_4w3_mg
      t.decimal :c20_2_mg
      t.decimal :c20_2w6_mg
      t.decimal :c20_3_mg
      t.decimal :c20_3w3_mg
      t.decimal :c20_3w6_mg
      t.decimal :c20_4_g
      t.decimal :c20_4w3_mg
      t.decimal :c20_4w6_mg
      t.decimal :c20_5w3_mg
      t.decimal :c21_5w3_g
      t.decimal :c22_5w3_mg
      t.decimal :c22_4w6_mg
      t.decimal :c22_2_g
      t.decimal :c22_2w6_mg
      t.decimal :c22_5w6_g
      t.decimal :c22_6w3_mg
      t.decimal :total_polyunsaturated_fatty_acids_equated_g
      t.decimal :total_long_chain_omega_3_fatty_acids_equated_mg
      t.decimal :total_undifferentiated_fatty_acids_mass_basis_basis_mg
      t.decimal :total_trans_fatty_acids_imputed_mg
      t.decimal :caffeine_mg
      t.decimal :cholesterol_mg
      t.decimal :alanine_mg_gn
      t.decimal :arginine_mg_gn
      t.decimal :aspartic_acid_mg_gn
      t.decimal :cystine_plus_cysteine_mg_gn
      t.decimal :glutamic_acid_mg_gn
      t.decimal :glycine_mg_gn
      t.decimal :histidine_mg_gn
      t.decimal :isoleucine_mg_gn
      t.decimal :leucine_mg_gn
      t.decimal :lysine_mg_gn
      t.decimal :methionine_mg_gn
      t.decimal :phenylalanine_mg_gn
      t.decimal :proline_mg_gn
      t.decimal :serine_mg_gn
      t.decimal :threonine_mg_gn
      t.decimal :tyrosine_mg_gn
      t.decimal :tryptophan_mg_gn
      t.decimal :valine_mg_gn
      t.decimal :alanine_mg
      t.decimal :arginine_mg
      t.decimal :aspartic_acid_mg
      t.decimal :cystine_plus_cysteine_mg
      t.decimal :glutamic_acid_mg
      t.decimal :glycine_mg
      t.decimal :histidine_mg
      t.decimal :isoleucine_mg
      t.decimal :leucine_mg
      t.decimal :lysine_mg
      t.decimal :methionine_mg
      t.decimal :phenylalanine_mg
      t.decimal :proline_mg
      t.decimal :serine_mg
      t.decimal :threonine_mg
      t.decimal :tyrosine_mg
      t.decimal :tryptophan_mg
      t.decimal :valine_mg

      t.timestamps
    end
  end
end
