require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CropsController do

  # This should return the minimal set of attributes required to create a valid
  # Crop. As you add validations to Crop, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CropsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all crops as @crops" do
      crop = Crop.create! valid_attributes
      get :index, {}, valid_session
      assigns(:crops).should eq([crop])
    end
  end

  describe "GET show" do
    it "assigns the requested crop as @crop" do
      crop = Crop.create! valid_attributes
      get :show, {:id => crop.to_param}, valid_session
      assigns(:crop).should eq(crop)
    end
  end

  describe "GET new" do
    it "assigns a new crop as @crop" do
      get :new, {}, valid_session
      assigns(:crop).should be_a_new(Crop)
    end
  end

  describe "GET edit" do
    it "assigns the requested crop as @crop" do
      crop = Crop.create! valid_attributes
      get :edit, {:id => crop.to_param}, valid_session
      assigns(:crop).should eq(crop)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Crop" do
        expect {
          post :create, {:crop => valid_attributes}, valid_session
        }.to change(Crop, :count).by(1)
      end

      it "assigns a newly created crop as @crop" do
        post :create, {:crop => valid_attributes}, valid_session
        assigns(:crop).should be_a(Crop)
        assigns(:crop).should be_persisted
      end

      it "redirects to the created crop" do
        post :create, {:crop => valid_attributes}, valid_session
        response.should redirect_to(Crop.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved crop as @crop" do
        # Trigger the behavior that occurs when invalid params are submitted
        Crop.any_instance.stub(:save).and_return(false)
        post :create, {:crop => {}}, valid_session
        assigns(:crop).should be_a_new(Crop)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Crop.any_instance.stub(:save).and_return(false)
        post :create, {:crop => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested crop" do
        crop = Crop.create! valid_attributes
        # Assuming there are no other crops in the database, this
        # specifies that the Crop created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Crop.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => crop.to_param, :crop => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested crop as @crop" do
        crop = Crop.create! valid_attributes
        put :update, {:id => crop.to_param, :crop => valid_attributes}, valid_session
        assigns(:crop).should eq(crop)
      end

      it "redirects to the crop" do
        crop = Crop.create! valid_attributes
        put :update, {:id => crop.to_param, :crop => valid_attributes}, valid_session
        response.should redirect_to(crop)
      end
    end

    describe "with invalid params" do
      it "assigns the crop as @crop" do
        crop = Crop.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Crop.any_instance.stub(:save).and_return(false)
        put :update, {:id => crop.to_param, :crop => {}}, valid_session
        assigns(:crop).should eq(crop)
      end

      it "re-renders the 'edit' template" do
        crop = Crop.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Crop.any_instance.stub(:save).and_return(false)
        put :update, {:id => crop.to_param, :crop => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested crop" do
      crop = Crop.create! valid_attributes
      expect {
        delete :destroy, {:id => crop.to_param}, valid_session
      }.to change(Crop, :count).by(-1)
    end

    it "redirects to the crops list" do
      crop = Crop.create! valid_attributes
      delete :destroy, {:id => crop.to_param}, valid_session
      response.should redirect_to(crops_url)
    end
  end

end
