require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HarvestsController do

  # This should return the minimal set of attributes required to create a valid
  # Harvest. As you add validations to Harvest, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "crop_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HarvestsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all harvests as @harvests" do
      harvest = Harvest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:harvests).should eq([harvest])
    end
  end

  describe "GET show" do
    it "assigns the requested harvest as @harvest" do
      harvest = Harvest.create! valid_attributes
      get :show, {:id => harvest.to_param}, valid_session
      assigns(:harvest).should eq(harvest)
    end
  end

  describe "GET new" do
    it "assigns a new harvest as @harvest" do
      get :new, {}, valid_session
      assigns(:harvest).should be_a_new(Harvest)
    end
  end

  describe "GET edit" do
    it "assigns the requested harvest as @harvest" do
      harvest = Harvest.create! valid_attributes
      get :edit, {:id => harvest.to_param}, valid_session
      assigns(:harvest).should eq(harvest)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Harvest" do
        expect {
          post :create, {:harvest => valid_attributes}, valid_session
        }.to change(Harvest, :count).by(1)
      end

      it "assigns a newly created harvest as @harvest" do
        post :create, {:harvest => valid_attributes}, valid_session
        assigns(:harvest).should be_a(Harvest)
        assigns(:harvest).should be_persisted
      end

      it "redirects to the created harvest" do
        post :create, {:harvest => valid_attributes}, valid_session
        response.should redirect_to(Harvest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved harvest as @harvest" do
        # Trigger the behavior that occurs when invalid params are submitted
        Harvest.any_instance.stub(:save).and_return(false)
        post :create, {:harvest => { "crop_id" => "invalid value" }}, valid_session
        assigns(:harvest).should be_a_new(Harvest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Harvest.any_instance.stub(:save).and_return(false)
        post :create, {:harvest => { "crop_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested harvest" do
        harvest = Harvest.create! valid_attributes
        # Assuming there are no other harvests in the database, this
        # specifies that the Harvest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Harvest.any_instance.should_receive(:update_attributes).with({ "crop_id" => "1" })
        put :update, {:id => harvest.to_param, :harvest => { "crop_id" => "1" }}, valid_session
      end

      it "assigns the requested harvest as @harvest" do
        harvest = Harvest.create! valid_attributes
        put :update, {:id => harvest.to_param, :harvest => valid_attributes}, valid_session
        assigns(:harvest).should eq(harvest)
      end

      it "redirects to the harvest" do
        harvest = Harvest.create! valid_attributes
        put :update, {:id => harvest.to_param, :harvest => valid_attributes}, valid_session
        response.should redirect_to(harvest)
      end
    end

    describe "with invalid params" do
      it "assigns the harvest as @harvest" do
        harvest = Harvest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Harvest.any_instance.stub(:save).and_return(false)
        put :update, {:id => harvest.to_param, :harvest => { "crop_id" => "invalid value" }}, valid_session
        assigns(:harvest).should eq(harvest)
      end

      it "re-renders the 'edit' template" do
        harvest = Harvest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Harvest.any_instance.stub(:save).and_return(false)
        put :update, {:id => harvest.to_param, :harvest => { "crop_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested harvest" do
      harvest = Harvest.create! valid_attributes
      expect {
        delete :destroy, {:id => harvest.to_param}, valid_session
      }.to change(Harvest, :count).by(-1)
    end

    it "redirects to the harvests list" do
      harvest = Harvest.create! valid_attributes
      delete :destroy, {:id => harvest.to_param}, valid_session
      response.should redirect_to(harvests_url)
    end
  end

end
